name: Build and Upload ASP.Net Core App - SaleafApi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4

      # Step 2: Set up .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      # Step 3: Restore dependencies (specify solution or project file)
      - name: Install dependencies
        run: dotnet restore SaleafApi.sln

      # Step 4: Build the application
      - name: Build with dotnet
        run: dotnet build SaleafApi.sln --configuration Release

      # Step 5: Publish the application
      - name: Publish with dotnet
        run: dotnet publish SaleafApi.sln --configuration Release --output ${{env.RUNNER_TEMP}}\myapp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.RUNNER_TEMP}}\myapp
